/**
 * withShareIntentAndroid.js  —  Expo Config Plugin (EAS-safe)
 *
 * Survives expo prebuild / EAS Build by patching all generated native files:
 *
 *   1. AndroidManifest.xml  — ACTION_SEND + ACTION_VIEW intent filters
 *   2. MainActivity.kt      — handleShareIntent, onNewIntent, emitShareIntent
 *   3. MainApplication.kt   — ShareIntentPackage registration
 *   4. ShareIntentModule.kt — written if missing (not regenerated by prebuild)
 *   5. ShareIntentPackage.kt— written if missing (not regenerated by prebuild)
 *
 * All patching is idempotent — sentinel strings prevent double-application.
 *
 * Reference: https://docs.expo.dev/config-plugins/introduction/
 */

const {
  withAndroidManifest,
  withMainActivity,
  withMainApplication,
} = require('@expo/config-plugins');
const path = require('path');
const fs   = require('fs');

// ─────────────────────────────────────────────────────────────────────────────
// PART 1 — AndroidManifest.xml  (intent filters + READ_MEDIA_AUDIO permission)
// ─────────────────────────────────────────────────────────────────────────────

const SHARE_INTENT_FILTERS = [
  { action: 'android.intent.action.SEND', mime: 'audio/*' },
  { action: 'android.intent.action.SEND', mime: 'application/octet-stream' },
  { action: 'android.intent.action.VIEW', mime: 'audio/*' },
  { action: 'android.intent.action.VIEW', mime: 'audio/opus' },
  { action: 'android.intent.action.VIEW', mime: 'audio/ogg' },
  { action: 'android.intent.action.VIEW', mime: 'audio/aac' },
  { action: 'android.intent.action.VIEW', mime: 'audio/mpeg' },
  { action: 'android.intent.action.VIEW', mime: 'audio/mp4' },
];

function hasIntentFilter(existing, actionName, mimeType) {
  if (!existing) return false;
  return existing.some((f) => {
    const hasAction = (f.action || []).some((a) => a?.$?.['android:name'] === actionName);
    const hasMime   = (f.data   || []).some((d) => d?.$?.['android:mimeType'] === mimeType);
    return hasAction && hasMime;
  });
}

function patchManifest(config) {
  return withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;

    // Ensure READ_MEDIA_AUDIO permission (Android 13+)
    const perms = manifest['uses-permission'] || [];
    if (!perms.some((p) => p?.$?.['android:name'] === 'android.permission.READ_MEDIA_AUDIO')) {
      perms.push({ $: { 'android:name': 'android.permission.READ_MEDIA_AUDIO' } });
      manifest['uses-permission'] = perms;
    }

    const mainActivity = (manifest.application?.[0]?.activity || [])
      .find((a) => a?.$?.['android:name'] === '.MainActivity');
    if (!mainActivity) return mod;

    if (!mainActivity['intent-filter']) mainActivity['intent-filter'] = [];
    const existing = mainActivity['intent-filter'];

    for (const { action, mime } of SHARE_INTENT_FILTERS) {
      if (!hasIntentFilter(existing, action, mime)) {
        existing.push({
          $: {},
          action:   [{ $: { 'android:name': action } }],
          category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
          data:     [{ $: { 'android:mimeType': mime } }],
        });
      }
    }

    return mod;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// PART 2 — MainActivity.kt
// withMainActivity provides the source as mod.modResults.contents (string).
// We replace the entire file with our version when the sentinel is absent.
// ─────────────────────────────────────────────────────────────────────────────

// If this string is in the file, the patch is already applied — skip.
const MAIN_ACTIVITY_SENTINEL = 'handleShareIntent(intent)';

function buildMainActivity(packageName) {
  return `package ${packageName}

import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.util.Log

import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.ReactInstanceManager
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.ReactContext
import com.facebook.react.bridge.WritableMap
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import com.facebook.react.modules.core.DeviceEventManagerModule

import expo.modules.ReactActivityDelegateWrapper

class MainActivity : ReactActivity() {

  companion object {
    private const val TAG = "ShareIntent"
  }

  override fun onCreate(savedInstanceState: Bundle?) {
    setTheme(R.style.AppTheme)
    super.onCreate(null)
    Log.d(TAG, "onCreate action=\${intent?.action} type=\${intent?.type}")
    handleShareIntent(intent)
  }

  override fun onNewIntent(intent: Intent?) {
    super.onNewIntent(intent)
    Log.d(TAG, "onNewIntent action=\${intent?.action} type=\${intent?.type}")
    intent?.let { handleShareIntent(it) }
  }

  private fun handleShareIntent(intent: Intent) {
    if (intent.action != Intent.ACTION_SEND && intent.action != Intent.ACTION_VIEW) return

    val uri: Uri? = when (intent.action) {
      Intent.ACTION_SEND -> {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
          intent.getParcelableExtra(Intent.EXTRA_STREAM, Uri::class.java)
        } else {
          @Suppress("DEPRECATION")
          intent.getParcelableExtra(Intent.EXTRA_STREAM)
        }
      }
      else -> intent.data
    }

    if (uri == null) {
      Log.w(TAG, "handleShareIntent: URI is null — aborting")
      return
    }

    val mimeType  = intent.type ?: ""
    val uriString = uri.toString()
    Log.d(TAG, "handleShareIntent uri=\$uriString  mime=\$mimeType")

    // Store for JS pull (cold-start Path B)
    ShareIntentModule.pendingUri      = uriString
    ShareIntentModule.pendingMimeType = mimeType

    // Attempt immediate emit (foreground Path A)
    val currentCtx = reactInstanceManager?.currentReactContext
    if (currentCtx != null) {
      emitShareIntent(currentCtx, uriString, mimeType)
    } else {
      reactInstanceManager?.addReactInstanceEventListener(
        object : ReactInstanceManager.ReactInstanceEventListener {
          override fun onReactContextInitialized(ctx: ReactContext) {
            emitShareIntent(ctx, uriString, mimeType)
          }
        }
      )
    }
  }

  private fun emitShareIntent(ctx: ReactContext, uri: String, mimeType: String) {
    Log.d(TAG, "emitShareIntent uri=\$uri")
    val params: WritableMap = Arguments.createMap().apply {
      putString("uri", uri)
      putString("mimeType", mimeType)
    }
    ctx
      .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
      .emit("ShareIntentReceived", params)
  }

  override fun getMainComponentName(): String = "main"

  override fun createReactActivityDelegate(): ReactActivityDelegate =
    ReactActivityDelegateWrapper(
      this,
      BuildConfig.IS_NEW_ARCHITECTURE_ENABLED,
      object : DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled) {},
    )

  override fun invokeDefaultOnBackPressed() {
    if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.R) {
      if (!moveTaskToBack(false)) super.invokeDefaultOnBackPressed()
      return
    }
    super.invokeDefaultOnBackPressed()
  }
}
`;
}

function patchMainActivity(config) {
  return withMainActivity(config, (mod) => {
    if (mod.modResults.contents.includes(MAIN_ACTIVITY_SENTINEL)) {
      return mod; // already patched
    }
    const packageMatch = mod.modResults.contents.match(/^package\s+([\w.]+)/m);
    const packageName  = packageMatch?.[1] ?? (config.android?.package ?? 'com.placeholder');
    mod.modResults.contents = buildMainActivity(packageName);
    return mod;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// PART 3 — MainApplication.kt
// withMainApplication provides the source as mod.modResults.contents (string).
// ─────────────────────────────────────────────────────────────────────────────

const MAIN_APPLICATION_SENTINEL = 'ShareIntentPackage()';

function buildMainApplication(packageName) {
  return `package ${packageName}

import android.app.Application
import android.content.res.Configuration

import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.ReactHost
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.soloader.SoLoader

import expo.modules.ApplicationLifecycleDispatcher
import expo.modules.ReactNativeHostWrapper

class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost = ReactNativeHostWrapper(
        this,
        object : DefaultReactNativeHost(this) {
          override fun getPackages(): List<ReactPackage> {
            val packages = PackageList(this).packages.toMutableList()
            packages.add(ShareIntentPackage())
            return packages
          }

          override fun getJSMainModuleName(): String = ".expo/.virtual-metro-entry"

          override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

          override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
          override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }
  )

  override val reactHost: ReactHost
    get() = ReactNativeHostWrapper.createReactHost(applicationContext, reactNativeHost)

  override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, false)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      load()
    }
    ApplicationLifecycleDispatcher.onApplicationCreate(this)
  }

  override fun onConfigurationChanged(newConfig: Configuration) {
    super.onConfigurationChanged(newConfig)
    ApplicationLifecycleDispatcher.onConfigurationChanged(this, newConfig)
  }
}
`;
}

function patchMainApplication(config) {
  return withMainApplication(config, (mod) => {
    if (mod.modResults.contents.includes(MAIN_APPLICATION_SENTINEL)) {
      return mod; // already patched
    }
    const packageMatch = mod.modResults.contents.match(/^package\s+([\w.]+)/m);
    const packageName  = packageMatch?.[1] ?? (config.android?.package ?? 'com.placeholder');
    mod.modResults.contents = buildMainApplication(packageName);
    return mod;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// PART 4 — Ensure ShareIntentModule.kt and ShareIntentPackage.kt exist
// These are NOT regenerated by prebuild.  Write them if missing so a clean
// EAS environment (fresh git clone) also gets them.
// ─────────────────────────────────────────────────────────────────────────────

function buildShareIntentModule(packageName) {
  return `package ${packageName}

import android.util.Log
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.WritableMap
import com.facebook.react.bridge.Arguments

class ShareIntentModule(reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext) {

  companion object {
    private const val TAG = "ShareIntent"
    const val MODULE_NAME = "ShareIntentModule"

    @Volatile var pendingUri:      String? = null
    @Volatile var pendingMimeType: String? = null
  }

  override fun getName(): String = MODULE_NAME

  @ReactMethod
  fun getPendingIntent(promise: Promise) {
    val uri  = pendingUri
    val mime = pendingMimeType

    if (uri != null) {
      Log.d(TAG, "getPendingIntent: uri=\$uri")
      pendingUri      = null
      pendingMimeType = null
      val map: WritableMap = Arguments.createMap().apply {
        putString("uri",      uri)
        putString("mimeType", mime ?: "")
      }
      promise.resolve(map)
    } else {
      Log.d(TAG, "getPendingIntent: nothing pending")
      promise.resolve(null)
    }
  }
}
`;
}

function buildShareIntentPackage(packageName) {
  return `package ${packageName}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

class ShareIntentPackage : ReactPackage {
  override fun createNativeModules(
    reactContext: ReactApplicationContext,
  ): List<NativeModule> = listOf(ShareIntentModule(reactContext))

  override fun createViewManagers(
    reactContext: ReactApplicationContext,
  ): List<ViewManager<*, *>> = emptyList()
}
`;
}

function ensureNativeFiles(config) {
  // Use withMainActivity as a timing hook — by the time it runs, the android/
  // source tree exists.  We only need it for its side-effect (timing), not its
  // mod.modResults.contents output.
  return withMainActivity(config, (mod) => {
    const packageName = config.android?.package ?? 'com.placeholder';
    const packagePath = packageName.replace(/\./g, '/');

    // Derive the src directory from the MainActivity file path
    const mainActivityPath = mod.modResults.path;
    if (!mainActivityPath) return mod;

    const srcDir = path.dirname(mainActivityPath); // …/java/com/yourcompany/audioconverter/

    const toWrite = [
      { name: 'ShareIntentModule.kt',  content: buildShareIntentModule(packageName) },
      { name: 'ShareIntentPackage.kt', content: buildShareIntentPackage(packageName) },
    ];

    for (const { name, content } of toWrite) {
      const filePath = path.join(srcDir, name);
      if (!fs.existsSync(filePath)) {
        fs.mkdirSync(srcDir, { recursive: true });
        fs.writeFileSync(filePath, content, 'utf8');
      }
    }

    return mod;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// COMPOSE
// ─────────────────────────────────────────────────────────────────────────────

module.exports = function withShareIntentAndroid(config) {
  config = patchManifest(config);
  config = patchMainActivity(config);
  config = patchMainApplication(config);
  config = ensureNativeFiles(config);
  return config;
};
